### PR TITLE
Add support for automatically continue rebase after commit

### PR DESCRIPTION
**Pull request by jacob-carlborg**
Depends on this TextMate pull request: https://github.com/textmate/textmate/pull/1307, but it should be backwards compatible.

### CODE REVIEW

**Comment by sorbits** [comment]
In the TextMate pull request you wrote you used environment variable for backwards compatibility.

Do you mean that it was done so that this bundle can be used with older versions of TextMate?

If so, put a line like this in the commit message: `Requires TextMate 2.0-beta.8.2` (next version). The auto-updater will use that info to not auto-update the bundle if the requirement is not met.

With that, I think a command line option should be used rather than an environment variable, since we’re adding code complexity to support the environment variable, yet command line is what would normally be done.

**Comment by jacob-carlborg** [comment]
> Do you mean that it was done so that this bundle can be used with older versions of TextMate?

Yes.

> If so, put a line like this in the commit message: Requires TextMate 2.0-beta.8.2 (next version). The auto-updater will use that info to not auto-update the bundle if the requirement is not met.

Anywhere in the commit message?

> With that, I think a command line option should be used rather than an environment variable, since we’re adding code complexity to support the environment variable, yet command line is what would normally be done.

I agree.

**Comment by sorbits** [comment]
Yes, you can put the requirement anywhere in the commit message.

You can also put `#ignore` in the commit message to have it not show up 
in TextMate → About → Bundles (for example the “Strip 
whitespace” commit).

And for sake of completeness, the regexp used to find requirements is 
the following: /\b[Rr]equires?(?: TextMate)? 
v?(\d+(?:\.\d+){1,2})(-[[:alnum:]]+(?:\.[[:alnum:]]+)*)?(\+[[:alnum:]]+(?:\.[[:alnum:]]+)*)?\b/

So you have some flexibility in how you write it.

**Comment by jacob-carlborg** [comment]
Ok, cool, thanks.

**Comment by jacob-carlborg** [comment]
Updated, now uses the `--show-commit-and-continue-button` instead of the environment variable.

**Comment by jacob-carlborg** [comment]
Update based on the changes in TextMate master. Also fixed the commit messages according to the comments.

**Comment by jacob-carlborg** [comment]
@sorbits @infininight ping

**Comment by jacob-carlborg** [comment]
Thanks.

**Comment by sorbits** [comment]
Thank you for the commit and sorry about the delay.

**Comment by jacob-carlborg** [comment]
No worries :smiley:

**Pull request merged**
